name: Appium CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set APK Path
        run: echo "APK_PATH=$(echo $GITHUB_WORKSPACE)/app/app-koalaLabs-staging-release.apk" >> $GITHUB_ENV

      - name: Install AVD files
        run: |
          yes | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-34;default;x86_64'
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - name: Create Android emulator
        run: |
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_API_34_AOSP -d pixel --package 'system-images;android-34;default;x86_64' --force
          emulator_config=~/.android/avd/Pixel_API_34_AOSP.avd/config.ini
          sed -i .bak 's/hw.lcd.density=.*/hw.lcd.density=420/' "$emulator_config"
          sed -i .bak 's/hw.lcd.height=.*/hw.lcd.height=1920/' "$emulator_config"
          sed -i .bak 's/hw.lcd.width=.*/hw.lcd.width=1080/' "$emulator_config"
          if ! grep -q "hw.lcd.density" "$emulator_config"; then
            echo "hw.lcd.density=420" >> "$emulator_config"
          fi
          if ! grep -q "hw.lcd.height" "$emulator_config"; then
            echo "hw.lcd.height=1920" >> "$emulator_config"
          fi
          if ! grep -q "hw.lcd.width" "$emulator_config"; then
            echo "hw.lcd.width=1080" >> "$emulator_config"
          fi

      - name: Start Android emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd Pixel_API_34_AOSP -no-snapshot -no-window -no-audio -no-boot-anim -camera-back none -camera-front none -qemu -m 2048 > /dev/null 2>&1 &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'

      - name: Install Appium
        run: |
          sudo npm install -g appium
          sudo npm install -g appium@1.22.3
          sudo npm install -g appium-doctor

      - name: Download and Setup ChromeDriver for macOS
        run: |
          CHROMEDRIVER_VERSION=113.0.5672.63
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_mac64.zip
          unzip chromedriver_mac64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Start Appium Server with ChromeDriver Autodownload
        run: appium --allow-insecure chromedriver_autodownload --chromedriver-executable /usr/local/bin/chromedriver & appium-doctor
      - name: Check Appium Server
        run: pgrep -f "appium" || echo "Appium server is not running"

      - name: Run TestNG Tests
        run: mvn clean compile test

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Tests have completed running on GitHub Actions. See the workflow run at: $GITHUB_RUN_URL\"}" $SLACK_WEBHOOK_URL

      - name: 🐍 Python setup
        if: always()
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: 🚊 Install TestRail CLI
        if: always()
        run: pip install --upgrade trcli

      - name: ☁️ Upload test results to TestRail
        if: always()
        run: |
          cd ${{env.PROJECT_FOLDER}}
            # Upload test results to TestRail
            trcli -y \
            -h ${{ vars.TESTRAIL_HOST }} \
            --project "${{ vars.TESTRAIL_PROJECT_NAME }}" \
            --username ${{ vars.TESTRAIL_USERNAME }} \
            --key ${{ secrets.TESTRAIL_API_KEY }} \
            parse_junit \
            --title "[${{env.NOW}}]:[app: ${{env.APP_ENV}}]:[branch: ${{github.ref_name}}] - ${{env.TESTRAIL_TESTRUN_NAME}}" \
            --run-description "Smoke run is performed by https://github.com/Eftiar/Android_App_Appium_With_Java_Maven/actions/runs/8370790903. Purpose: validate that build is stable from main branch" \
            -f "$(echo $GITHUB_WORKSPACE)/target/surefire-reports/TEST-TestSuite.xml" \
 
 
